export type ValidSkills =
  | "Next.js"
  | "React"
  | "GraphQL"
  | "Nest.js"
  | "express.js"
  | "Node.js"
  | "MongoDB"
  | "Typescript"
  | "Javascript"
  | "HTML 5"
  | "CSS 3"
  | "React Native"
  | "Angular"
  | "Redux"
  | "Socket.io"
  | "Material UI"
  | "Tailwind CSS"
  | "AWS"
  | "Bootstrap"
  | "Google Auth"
  | "MySQL"
  | "Java"
  | "Databricks"
  | "Python"
  | "Docker"
  | "Kubernetes"
  | "PostgreSQL"
  | "Redis"
  | "Git"
  | "CI/CD"
  | "Jenkins"
  | "FastAPI"
  | "Django"
  | "Vue.js"
  | "Sass"
  | "Firebase"
  | "Azure"
  | "Google Cloud"
  | "Figma"
  | "Webpack"
  | "Jest"
  | "Cypress"
  | "Storybook"
  | "Prisma"
  | "Supabase"
  | "Vercel"
  | "Netlify"
  | "Three.js"
  | "WebGL"
  | "TensorFlow"
  | "PyTorch"
  | "Spring Boot"
  | "Laravel"
  | "PHP"
  | "Flutter"
  | "Dart"
  | "Flask"
  | "Django"
  | "FastAPI"
  | "SQL"
  | "SQL Server"
  | "NoSQL"
  | "AngularJS"
  | "Framer Motion"
  | "Power BI"
  | "ETL"
  | "Data Analysis"
  | "Power Apps"
  | "Data Visualization"
  | "IT Support"
  | "Networking"
  | "System Administration"
  | "Troubleshooting"
  | "Accounting"
  | "IT Infrastructure"
  | "Property Management"
  | "Communication"
  | "Windows Server"
  | "cPanel"
  | "Web Development"
  | "Geospatial BI"
  | "Treasury Pricing"
  | "Scikit-Learn"
  | "Streamlit"
  | "Predictive Analytics"
  | "Pandas"
  | "Scikit-learn"
  | "SSRS"
  | "Automation"
  | "PowerShell";

export type ValidCategory =
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev"
  | "Mobile Dev"
  | "3D Modeling"
  | "Data Analysis"
  | "Power BI"
  | "SQL"
  | "Machine Learning"
  | "Python"
  | "AI"
  | "Data Engineering"
  | "ETL"
  | "Automation"
  | "PowerShell";

export type ValidExpType = "Personal" | "Professional";

export type ValidPages =
  | "home"
  | "skills"
  | "projects"
  | "experience"
  | "contact"
  | "contributions"
  | "resume";
